# Generated by Django 4.0.6 on 2022-08-03 19:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=20)),
                ('price', models.PositiveIntegerField(blank=True)),
                ('amount', models.PositiveIntegerField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.CharField(max_length=16)),
                ('status', models.CharField(choices=[('Created', 'Created'), ('Payed', 'Payed'), ('Sent', 'Sent'), ('Recived', 'Recived')], default='Created', max_length=7)),
                ('items', models.ManyToManyField(to='shop.item')),
            ],
        ),
    ]
