# Generated by Django 4.0.6 on 2022-08-08 22:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0002_order_count_alter_item_amount_alter_item_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='order_number',
            field=models.PositiveIntegerField(default=1, verbose_name='Номер заказа'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('Created', 'Created'), ('Payed', 'Payed'), ('Sent', 'Sent'), ('Received', 'Received')], default='Created', max_length=8, verbose_name='статус заказа'),
        ),
        migrations.AlterField(
            model_name='order',
            name='user',
            field=models.CharField(max_length=16, verbose_name='идентификатор пользователя'),
        ),
    ]
